AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Template WAF set up with sql injection rule.
Parameters:
  ALBArn:
    Description: >-
      Arn of loadbalancer
    Type: 'String'
    Default: arn:aws:elasticloadbalancing:us-east-1:862654540448:loadbalancer/app/awseb-AWSEB-NKHGWIY2SIV3/c7a6b65ba851b9b0
    ConstraintDescription: must be the arn.
 
Resources:  

  MyWebACL: 
    Type: "AWS::WAFv2::WebACL"
    Properties: 
      Name: "dotnethellowebacl"
      Scope: REGIONAL
      DefaultAction: 
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: Metrics
      Rules:
        - Name: RuleWithAWSManagedRules
          Priority: 0
          OverrideAction:
            Count: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RuleWithAWSManagedRulesMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules: []  
        - Name: BlockXssAttack
          Priority: 1
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BlockXssAttackMetric
          Statement:
            XssMatchStatement:
              FieldToMatch:
                AllQueryArguments: {}
              TextTransformations:
                - Priority: 1
                  Type: URL_DECODE 

        - Name: BlockSqlInjAttack
          Priority: 2
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BlockSqlAttackMetric
          Statement:
            SqliMatchStatement:
              FieldToMatch:
                AllQueryArguments: {}
              TextTransformations:
                - Priority: 1
                  Type: URL_DECODE
  PublicWAF:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Ref ALBArn
      WebACLArn: !GetAtt MyWebACL.Arn